# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

font_family     Liberation Mono
font_size 14.0
enable_audio_bell yes
visual_bell_duration 0.1
enabled_layouts horizontal,vertical,stack,grid
hide_window_decorations yes
tab_bar_edge top
tab_bar_style powerline

# Add this to create the right-aligned date/time
tab_separator "{fmt.fg.tab}{fmt.bg.tab}"
tab_activity_symbol "🔔 "




background_opacity 0.90
dynamic_background_opacity yes
allow_remote_control yes
wayland_titlebar_color #000000
background_opacity 0.8
dynamic_background_opacity yes
map cmd+c        copy_to_clipboard
map cmd+v        paste_from_clipboard
map shift+insert paste_from_clipboard
enabled_layouts tall:bias=50;full_size=1;mirrored=false,stack
map kitty_mod+f5 load_config_file
map kitty_mod+[ layout_action decrease_num_full_size_windows
map kitty_mod+] layout_action increase_num_full_size_windows
map kitty_mod+/ layout_action mirror toggle
map kitty_mod+y layout_action mirror true
map kitty_mod+n layout_action mirror false
map kitty_mod+a toggle_layout tall
map kitty_mod+m toggle_maximized
map kitty_mod+z toggle_layout stack
map cmd+left previous_tab
map cmd+right next_tab

start_as fullscreen
background_opacity 0.9

shell /opt/homebrew/bin/bash
include ~/.config/kitty/kitty-themes/themes/Hybrid.conf
startup_session ~/.config/kitty/my-session.conf

macos_traditional_fullscreen no
macos_window_resizable yes
macos_quit_when_last_window_closed yes
macos_window_resizable yes
term xterm-256color

scrollback_pager nvim -u NONE -R -M -c 'lua require("kitty+page")(INPUT_LINE_NUMBER, CURSOR_LINE, CURSOR_COLUMN)' -

