model_reasoning_effort = "high"
model = "gpt-5.5"
personality = "pragmatic"
service_tier = "fast"
cli_auth_credentials_store = "auto"

[projects."/Users/arbeitandy/src/public/mirubato"]
trust_level = "trusted"

[projects."/Users/arbeitandy/src/public/0x5a"]
trust_level = "trusted"

[projects."/Users/arbeitandy/src/public/0x59"]
trust_level = "trusted"

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[plugins."github@openai-curated"]
enabled = true

[tui.model_availability_nux]
"gpt-5.5" = 1
